apiVersion: apps/v1
kind: Deployment
metadata:
  name: configtest
spec:
  selector:
    matchLabels:
      app: configtest
  template:
    metadata:
      labels:
        app: configtest
    spec:
      containers:
      - name: configtest
        env:
          - name: GREETING_NAME
            value: "Developers"
        args:
          - "-name=$(GREETING_NAME)!"
        image: configtest:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 8090
