apiVersion: apps/v1
kind: Deployment
metadata:
  name: configtest
spec:
  selector:
    matchLabels:
      app: configtest
  template:
    metadata:
      labels:
        app: configtest
    spec:
      containers:
      - name: configtest
        env:
          - name: GREETING_DEVS
            value: "Developers"
          - name: GREETING_TESTERS
            value: "Testers"
          - name: GREETING_FROM
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: GREETING_NAME
            value: "$(GREETING_DEVS) and $(GREETING_TESTERS) from $(GREETING_FROM)"
        image: configtest:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 8090
