apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configtest.fullname" . }}
  labels:
    {{- include "configtest.labels" . | nindent 4 }}
data:
  GREETING_NAME: {{ .Values.greetingName }}
