apiVersion: apps/v1
kind: Deployment
metadata:
  name: configtest
spec:
  selector: {}
  template:
    spec:
      containers:
      - name: configtest
        envFrom:
          - configMapRef:
              name: configtest
        image: configtest:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 8090
