apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomconfig
commonLabels:
  app.kubernetes.io/instance: configtest
  app.kubernetes.io/name: configtest
  app.kubernetes.io/managed-by: kustomize
resources:
  - namespace.yaml
  - deploy.yaml
  - service.yaml
configMapGenerator:
  - name: configtest
    env: configtest.env
